apiVersion: v1
kind: Namespace
metadata:
  name: "2401115"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-builder-app
  namespace: "2401115"
spec:
  replicas: 1

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: resume-builder-app

  template:
    metadata:
      labels:
        app: resume-builder-app
    spec:
      terminationGracePeriodSeconds: 10

      imagePullSecrets:
        - name: nexus-secret

      containers:
        - name: resume-builder-app
          image: nexus.nexus.svc.cluster.local:8085/my-repository/resume-builder-app:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 80

          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 5"]

          startupProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: 30
            periodSeconds: 2

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 2
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: resume-builder-service
  namespace: "2401115"
spec:
  selector:
    app: resume-builder-app
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: "2401115"
spec:
  selector:
    app: resume-builder-app
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: resume-builder-ingress
  namespace: "2401115"
spec:
  ingressClassName: nginx
  rules:
    - host: 2401115.imcc.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: client-service
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: resume-builder-service
                port:
                  number: 80
