apiVersion: v1
kind: Namespace
metadata:
  name: "2401115"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-builder-app
  namespace: "2401115"
  labels:
    app: resume-builder
spec:
  replicas: 1

  progressDeadlineSeconds: 180

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: resume-builder

  template:
    metadata:
      labels:
        app: resume-builder
    spec:
      terminationGracePeriodSeconds: 10

      imagePullSecrets:
        - name: nexus-secret

      containers:
        - name: resume-builder
          # ✅ FIXED IMAGE (NodeIP + NodePort)
          image: 127.0.0.1:30085/my-repository/resume-builder-app:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 80

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 5"]

          # Startup probe
          startupProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: 30
            periodSeconds: 2

          # Readiness probe
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

          # Liveness probe
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: resume-builder-service
  namespace: "2401115"
spec:
  type: ClusterIP
  selector:
    app: resume-builder
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: resume-builder-ingress
  namespace: "2401115"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: 2401115.imcc.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: resume-builder-service
                port:
                  number: 80
