apiVersion: v1
kind: Namespace
metadata:
  name: "2401115"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-builder-app
  namespace: "2401115"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resume-builder-app
  template:
    metadata:
      labels:
        app: resume-builder-app
    spec:
      imagePullSecrets:
        - name: nexus-docker-secret
      containers:
        - name: resume-builder-app
          image: nexus-service-for-docker-hosted-registry.nexus.svc.cluster.local:8085/my-repository/v2/2401115/resume-builder-app:__BUILD_NUMBER__
          imagePullPolicy: Always
          ports:
            - containerPort: 80

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: resume-builder-service
  namespace: "2401115"
spec:
  selector:
    app: resume-builder-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30085
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: resume-builder-ingress
  namespace: "2401115"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: 2401115.imcc.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: resume-builder-service
                port:
                  number: 80
