apiVersion: v1
kind: Service
metadata:
  name: resume-builder-service
  namespace: jenkins
spec:
  type: NodePort
  selector:
    app: resume-builder-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30085
